---
- name: "Ensure the {{ nginx_user }} user is present."
  user:
    name: "{{ nginx_user }}"
    home: "{{ nginx_homedir }}"
    shell: /usr/sbin/nologin
    system: yes

- name: Distribution specific installation
  include: "install_{{ ansible_distribution }}.yml"
  tags:
    - install

- name: Generate strong Diffie-Hellman group. This can take a while.
  command: "/usr/bin/openssl dhparam -out /etc/ssl/certs/dhparam.pem {{ nginx_dh_length }}"
  args:
    creates: "/etc/ssl/certs/dhparam.pem"

- name: Configure nginx
  include: "nginx.yml"
  tags:
    - nginx

- name: Configure certbot
  include: "certbot"
  tags:
    - certbot

