---
- name: Create vhost directories
  file:
    dest: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
  with_items:
    - sites-enabled
    - sites-available

- name: Main configuration file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Snippets & conf.d
  template:
    src: "{{ item }}/"
    dest: "{{ nginx_conf_dir }}/{{ item }}/"
  notify: Restart nginx
  with_items:
    - conf.d
    - snippets

# We do this before nginx is (re)started
# because we do not want to break a running
# nginx instance.
- name: Check configuration
  command: /usr/sbin/nginx -t

- name: Ensure nginx is enabled & running
  service:
    name: nginx
    state: started
    enabled: yes
